### ISSUE TITLE
17장 페이지 네비게이션 코드 문의드립니다.

### ISSUE THREAD

**Issue by mklinkj** [gilbutITbook/006895#89]
안녕하세요.

17장 페이지 네비게이션을 구현한 JSP 코드를 봤을 때, 이상한 점이 있어서 문의드립니다.

페이징 쿼리 SQL을 보면 쿼리의 WHERE 조건식 에서 section 기준으로 계산을 이미 하므로

리스트 JSP에서 컨트롤러로 전달하는 pageNum은 어떤 상황이든 항상 네비게이션의 순번값  (1 ~ 10) 그대로만 

전달하면 될 것으로 보이는데...

총 게시물 수가 100개를 초과했을 때.. 나타나는 pre와 next에 대한 아래 코드를 보면 ...

* pre
https://github.com/gilbutITbook/006895/blob/df5694f599cea256617db0db09f7f7d52e261f49/pro17/WebContent/board07/listArticles.jsp#L78

* next
https://github.com/gilbutITbook/006895/blob/df5694f599cea256617db0db09f7f7d52e261f49/pro17/WebContent/board07/listArticles.jsp#L82

pageNum을 네비게이션 순번 값으로 그대로 보내지 않고 불필요한 계산을 하는 모습이 보여서요.

위의 코드로 하면 1000개 이상의 게시물 데이터를 넣고 확인했을 때.. 제대로 동작하지 않았었는데..

이 부분 시간 되실 때.. 확인 한번 부탁드립니다. ✨

페이징 테스트를 위한 게시글 데이터 입력의 경우....

```sql
DECLARE
    i NUMBER := 15;
BEGIN
    WHILE(i <= 1015)
        LOOP
            INSERT INTO t17_board (article_no, parent_no, title, content, image_file_name, write_date, id)
            VALUES (i, 0, i||'테스트글입니다.', i||'테스트글입니다.', null, TO_DATE('2023-04-03 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'hong');
            i := i + 1;
END LOOP;
END;
COMMIT;
```

위의 코드 실행해서 입력 했습니다. (테이블 명, 컬럼은 책과 비교해서 약간 다르게 쓰긴 했어요..)

감사합니다.

---
아래는 누락 같은데..

https://github.com/gilbutITbook/006895/blob/df5694f599cea256617db0db09f7f7d52e261f49/pro17/WebContent/board07/listArticles.jsp#L88

글이 딱 100개였을 때의 조건에서는  페이지 네비게이션의 각 페이지 번호들의 링크가 동작하지 않게 되어있는 것 같습니다.

**Comment by leebs126** [comment]
안녕하세요.
책의 페이징 기능은 기본기능만 있고 완벽하지 않습니다.나머지 부분은 독자들이 구현해봄으로써 스스로 학습하는겁니다. 님께서 수정해서
적용하시면 될 것같습니다. 수고하세요^^


2023년 4월 6일 (목) 오후 4:34, mklinkj ***@***.***>님이 작성:

**Comment by mklinkj** [comment]
안녕하세요 빠른 답변 감사합니다.
