### ISSUE TITLE
943쪽 MemberVO 를 빈으로 설정하는 부분 문의드립니다.

### ISSUE THREAD

**Issue by mklinkj** [gilbutITbook/006895#90]
안녕하세요.

MemberVO 를 빈으로 설정하는 부분 문의드립니다.

MemberController의 addMember()메서드가 실행될 때.. 자동으로 MemberVO를 생성해서 전달해줄 텐데...

https://github.com/gilbutITbook/006895/blob/aae26fe4a0beb0f9b228e03258918e050103249b/pro26/src/com/spring/member/vo/MemberVO.java#L7

위처럼 싱글톤 빈을 일부러 만들 필요가 없어서 보여서 문의드렸습니다.

한번 검토 부탁드립니다. 

감사합니다. 좋은하루되세요.

**Comment by leebs126** [comment]
안녕하세요.
940p 코드26-22 필드에서 생성한 빈이 사용되고 있습니다. 질문은 제 카페를 통해서 해주세요.
감사합니다.

2023년 6월 6일 (화) 오후 5:37, mklinkj ***@***.***>님이 작성:

**Comment by mklinkj** [comment]
안녕하세요.

제가 질문을 상세하게 적질 못한 것 같네요.

다시 말씀드리면...

* MemberVO를 @Component 어노테이션을 붙여 싱글톤 빈을 만들 필요가 없지 않은지?
* 940쪽의 MemberControllerImpl 클래스의 MemberVO 필드는 의미가 없지 않은지?

의미가 없다고 생각한 이유는..

컨트롤러 메서드의 파라미터로 객체타입을 전달하면 요청이 들어올때마다 그 타입에 맞는 객체를 새로(new) 생성해줄 텐데... 컨트롤러의 private필드로 MemberVO를 쓰셨는지 해서 문의를 드린 것입니다.

```java
@Controller("memberController")
public class MemberControllerImpl implements MemberController {
  private static final Logger LOGGER = LoggerFactory.getLogger(MemberControllerImpl.class);

  @Autowired private MemberService memberService;

  // TODO: 아래 필드는 불필요해보임.
  @Autowired private MemberVO memberVO;

  // ....
  @Override
  @RequestMapping(value = "/member/addMember.do", method = RequestMethod.POST)
  public ModelAndView addMember(
      @ModelAttribute("member") MemberVO member,
      HttpServletRequest request,
      HttpServletResponse response)
      throws Exception {
    request.setCharacterEncoding("utf-8");

    LOGGER.info("### 필드의 memberVO:: {}", memberVO);
    LOGGER.info("### 인자로 전달받은 memberVO:: {}", member);
    LOGGER.info("### 두 VO가 같은지?:: {}", Objects.equals(memberVO, member));

    int result = 0;
    result = memberService.addMember(member);
    ModelAndView mav = new ModelAndView("redirect:/member/listMembers.do");
    return mav;
  }
  // ....
```

LOGGER를 찍어보면 간단히 알 수 있는데...
```
... 1번째 요청
INFO  com.spring.member.controller.MemberControllerImpl - ### 필드의 memberVO:: com.spring.member.vo.MemberVO@1ac134f5
INFO  com.spring.member.controller.MemberControllerImpl - ### 인자로 전달받은 memberVO:: com.spring.member.vo.MemberVO@45d54df8
INFO  com.spring.member.controller.MemberControllerImpl - ### 두 VO가 같은지?:: false
... 2번째 요청
INFO  com.spring.member.controller.MemberControllerImpl - ### 필드의 memberVO:: com.spring.member.vo.MemberVO@1ac134f5
INFO  com.spring.member.controller.MemberControllerImpl - ### 인자로 전달받은 memberVO:: com.spring.member.vo.MemberVO@5ed6da6
INFO  com.spring.member.controller.MemberControllerImpl - ### 두 VO가 같은지?:: false
... 3번째 요청
INFO  com.spring.member.controller.MemberControllerImpl - ### 필드의 memberVO:: com.spring.member.vo.MemberVO@1ac134f5
INFO  com.spring.member.controller.MemberControllerImpl - ### 인자로 전달받은 memberVO:: com.spring.member.vo.MemberVO@31946c40
INFO  com.spring.member.controller.MemberControllerImpl - ### 두 VO가 같은지?:: false
```
* 필드의 MemberVO는 항상 같은 객체이고, 컨트롤러 메서드 파라미터로 받는 MemberVO객체는 계속 달라지는 것을 알 수 있습니다.


결국은 정리를 하면...
1. `943쪽` MemberVO 클래스에 붙은  `@Component` 제거 필요
2. `940쪽` MemberControllerImpl 의 `@Autowired private MemberVO memberVO;` 필드 제거 필요

위와 같이 정리해야할 필요가 있다고 생각합니다.


* 동작 확인 코드 입니다.
  * https://github.com/mklinkj/006895-the-art-of-java-web-programming/tree/study/pro26-maven
  * 메이븐 빌드 적용, HSQLDB 메모리 모드, Jetty 플러그인을 적용했기 때문에... Java 17 환경만 맞춰주시면 바로 실행가능하십니다.


책은 아주 잘 보고 있습니다👍. 조금만 있으면 쇼핑몰이네요 😅

감사합니다.  그럼 좋은하루되세요.

**Comment by leebs126** [comment]
네, 맞습니다. 필드에 선언한 건 이란 식으로 빈을 autowired를 이용해서 사용할 수 있다는걸 보여주기 위함입니다.
좋은 두말되세요.

2023년 6월 11일 (일) 오전 10:17, mklinkj ***@***.***>님이 작성:
